# Generated by Django 4.0 on 2022-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id_from', models.IntegerField()),
                ('user_id_to', models.IntegerField()),
                ('date_write_message', models.CharField(max_length=16)),
                ('message_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messages_page',
            },
        ),
    ]
