# Generated by Django 4.0 on 2022-07-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('chat_win', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_id_to', models.IntegerField()),
                ('date_write', models.DateTimeField()),
                ('message_text', models.TextField()),
            ],
            options={
                'db_table': 'default_name',
            },
        ),
        migrations.AlterModelTable(
            name='chat',
            table='messages',
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('message_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.userfile')),
            ],
            options={
                'db_table': 'default',
            },
        ),
        migrations.CreateModel(
            name='MessagesTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_name', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.userfile')),
            ],
            options={
                'db_table': 'messages_data_table',
            },
        ),
    ]
