# Generated by Django 4.0 on 2022-05-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('user_login', models.CharField(max_length=150)),
                ('friend_id', models.IntegerField()),
                ('friend_firstname', models.CharField(max_length=150)),
                ('friend_lastname', models.CharField(max_length=150)),
                ('friend_login', models.CharField(max_length=150)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.userfile')),
            ],
            options={
                'db_table': 'friends_request',
            },
        ),
        migrations.CreateModel(
            name='FriendsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('user_login', models.CharField(max_length=150)),
                ('friend_id', models.IntegerField()),
                ('friend_firstname', models.CharField(max_length=150)),
                ('friend_lastname', models.CharField(max_length=150)),
                ('friend_login', models.CharField(max_length=150)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.userfile')),
            ],
            options={
                'db_table': 'friends_data',
            },
        ),
    ]
