# Generated by Django 4.0 on 2022-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=120)),
                ('friend_login', models.CharField(max_length=120)),
                ('friend_email', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('request_on_friend', models.BooleanField()),
                ('friend_id', models.IntegerField()),
            ],
            options={
                'db_table': '',
            },
        ),
    ]
