# Generated by Django 4.0 on 2022-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendsdata_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsdata',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='friendsrequest',
            name='user_id',
        ),
        migrations.AddField(
            model_name='friendsdata',
            name='date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='friendsdata',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
