# Generated by Django 4.0 on 2022-06-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.ImageField(upload_to='')),
                ('date_load', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photo_id', to='authorization.userfile')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
                'db_table': 'photos',
            },
        ),
    ]
