# Generated by Django 4.0 on 2022-05-30 12:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProFile',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=50)),
                ('city', models.TextField()),
                ('education', models.TextField()),
                ('university', models.TextField()),
                ('sex', models.CharField(max_length=1)),
                ('born_date', models.DateField()),
                ('job', models.TextField()),
                ('job_position', models.TextField()),
                ('receipt_date', models.DateField()),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'данные пользователя',
                'verbose_name_plural': 'данных пользователя',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128)),
                ('user_login', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('phone', models.CharField(max_length=14)),
                ('avatar', models.ImageField(upload_to='media/avatar/%Y/%m/%d')),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('first_login', models.DateTimeField()),
                ('last_join', models.TextField()),
                ('dateJoin', models.DateTimeField()),
                ('cover_photo', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('friend_mass', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('photo', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('community', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('buffer_zone', models.ImageField(upload_to='media/avatar/buffer/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'userfile',
            },
        ),
    ]
